import { versioned, type QualityReport, type SceneGraph, type SceneNode } from "@sparkdeck/presentation-model";
import { contrast } from "@sparkdeck/design-language";
const overlap=(a:SceneNode["bounds"],b:SceneNode["bounds"])=>a.x<b.x+b.width&&a.x+a.width>b.x&&a.y<b.y+b.height&&a.y+a.height>b.y;
export function evaluateScene(scene:SceneGraph):QualityReport{
 const issues:QualityReport["issues"]=[],signatures:string[]=[];for(const page of scene.pages){for(const node of page.nodes){const b=node.bounds;if(b.x<0||b.y<0||b.x+b.width>page.width+.01||b.y+b.height>page.height+.01)issues.push({code:"NODE_OVERFLOW",dimension:"Export",severity:"error",pageId:page.id,nodeIds:[node.id],message:"Node exceeds canvas"});if(node.kind==="text"){const size=Number(node.style.fontSize??0);if(size<16)issues.push({code:"FONT_TOO_SMALL",dimension:"Design",severity:"error",pageId:page.id,nodeIds:[node.id],message:"Text is below readable minimum"});const color=String(node.style.color??"#000000");if(/^#[0-9a-f]{6}$/i.test(color)&&contrast(color,page.background)<4.5)issues.push({code:"LOW_CONTRAST",dimension:"Design",severity:"error",pageId:page.id,nodeIds:[node.id],message:"Text contrast is insufficient"});}if(node.kind==="image"&&!node.content.assetId)issues.push({code:"ASSET_UNRESOLVED",dimension:"Content",severity:"warning",pageId:page.id,nodeIds:[node.id],message:"Media placement has no resolved asset"});}
  for(let i=0;i<page.nodes.length;i++)for(let j=i+1;j<page.nodes.length;j++){const a=page.nodes[i]!,b=page.nodes[j]!;if(a.kind!=="group"&&b.kind!=="group"&&overlap(a.bounds,b.bounds))issues.push({code:"NODE_OVERLAP",dimension:"Design",severity:"warning",pageId:page.id,nodeIds:[a.id,b.id],message:"Visible elements overlap"});}
  signatures.push(page.nodes.map(n=>`${n.kind}:${Math.round(n.bounds.x/page.width*10)}:${Math.round(n.bounds.y/page.height*10)}`).join("|"));}
 for(let i=1;i<signatures.length;i++)if(signatures[i]===signatures[i-1])issues.push({code:"REPETITIVE_COMPOSITION",dimension:"Coherence",severity:"warning",pageId:scene.pages[i]?.id,nodeIds:[],message:"Adjacent pages use the same composition silhouette"});
 const errorCounts={Content:0,Design:0,Coherence:0,Export:0};for(const issue of issues)if(issue.severity==="error")errorCounts[issue.dimension]++;const scores={Content:Math.max(0,100-errorCounts.Content*20),Design:Math.max(0,100-errorCounts.Design*15),Coherence:Math.max(0,100-errorCounts.Coherence*20),Export:Math.max(0,100-errorCounts.Export*25)};const visualReviewPageIds=scene.pages.filter((p,i)=>i===0||i===scene.pages.length-1||issues.some(issue=>issue.pageId===p.id)).map(p=>p.id);
 return versioned({presentationId:scene.presentationId,passed:!issues.some(i=>i.severity==="error"),scores,issues,visualReviewPageIds,repairCount:0},0,{scene:scene.contentHash});
}
export function buildVisualReviewBatch(scene:SceneGraph,report:QualityReport){return{sceneHash:scene.contentHash,pageIds:report.visualReviewPageIds,dimensions:["Content","Design","Coherence"] as const,contactSheetRequired:report.visualReviewPageIds.length>0};}
