import { hashContent, versioned, type AssetPlan, type NarrativeOutline, type PageDesignIntent, type SceneGraph, type SceneNode } from "@sparkdeck/presentation-model";
import type { DesignTokens } from "@sparkdeck/design-language";
import type { ResolvedCandidate, ResolvedCompositionNode } from "@sparkdeck/composition-engine";

const leaves=(node:ResolvedCompositionNode):ResolvedCompositionNode[]=>node.children.length?node.children.flatMap(leaves):[node];
export function compileSceneGraph(input:{presentationId:string;outline:NarrativeOutline;intents:PageDesignIntent[];candidateSets:ResolvedCandidate[][];tokens:DesignTokens;canvas:{width:number;height:number};assetPlan?:AssetPlan|undefined;assets?:Record<string,{url?:string|undefined;dataUri?:string|undefined;alt:string}>|undefined}):SceneGraph{
 const pages=input.outline.pages.map((page,index)=>{const set=input.candidateSets[index]??[],selected=set.find(c=>c.selected)??set[0];if(!selected)throw new Error(`Missing composition for ${page.id}`);const groups=new Map(page.contentGroups.map(g=>[g.id,g])),intent=input.intents.find(i=>i.pageId===page.id);const nodes:SceneNode[]=leaves(selected.resolved).filter(n=>["Text","Shape","Image","Chart","Connector"].includes(n.kind)).map((leaf,zIndex)=>{
  const group=leaf.sourceIds.map(id=>groups.get(id)).find(Boolean),media=input.assetPlan?.placements.find(p=>p.boundsRef===leaf.id||leaf.sourceIds.includes(p.requestId)),asset=media?.assetId?input.assets?.[media.assetId]:undefined,isTitle=leaf.props.role==="title";const kind=leaf.kind.toLowerCase() as SceneNode["kind"];
  const content=kind==="text"?{text:isTitle?page.headline:group?.text??group?.items?.join("\n")??group?.rows?.map(row=>row.join(" · ")).join("\n")??page.message,role:isTitle?"title":"body"}:kind==="image"?{placementId:media?.id,assetId:media?.assetId,url:asset?.url,dataUri:asset?.dataUri,alt:asset?.alt??intent?.mediaRequests.find(r=>leaf.sourceIds.includes(r.id))?.description??""}:{};
  const style=kind==="text"?{fontFamily:input.tokens.fontFamily,fontSize:isTitle?input.tokens.titlePt:input.tokens.bodyPt,fontWeight:isTitle?input.tokens.headingWeight:input.tokens.bodyWeight,color:input.tokens.text}:{fill:input.tokens.surface,stroke:input.tokens.accent,radius:input.tokens.radius};
  return{id:leaf.id,kind,sourceIds:leaf.sourceIds,bounds:leaf.bounds,zIndex,style,content,locked:false,contentHash:hashContent({content,style,bounds:leaf.bounds})};
 });return{id:page.id,width:input.canvas.width,height:input.canvas.height,background:input.tokens.background,nodes,selectedCandidateId:selected.id,alternativeCandidateIds:set.filter(c=>c.id!==selected.id).map(c=>c.id)};});
 return versioned({presentationId:input.presentationId,canvas:{...input.canvas,unit:"pt" as const},theme:input.tokens,pages},0,{outline:input.outline.contentHash});
}
export function sceneSemanticFingerprint(scene:SceneGraph){return hashContent({canvas:scene.canvas,theme:scene.theme,pages:scene.pages.map(p=>({id:p.id,nodes:p.nodes.map(n=>({id:n.id,kind:n.kind,sourceIds:n.sourceIds,bounds:n.bounds,contentHash:n.contentHash}))}))});}
export function applySceneCommand(scene:SceneGraph,command:{type:"set-text"|"set-bounds"|"set-z"|"set-asset"|"set-crop";pageId:string;nodeId:string;value:unknown;expectedRevision:number}):SceneGraph{
 if(scene.revision!==command.expectedRevision)throw new Error("REVISION_CONFLICT");const pages=scene.pages.map(page=>page.id!==command.pageId?page:{...page,nodes:page.nodes.map(node=>{if(node.id!==command.nodeId)return node;if(command.type==="set-text"&&node.kind==="text")return{...node,content:{...node.content,text:String(command.value)}};if(command.type==="set-bounds")return{...node,bounds:command.value as SceneNode["bounds"]};if(command.type==="set-z")return{...node,zIndex:Number(command.value)};if(command.type==="set-asset"&&node.kind==="image")return{...node,content:{...node.content,url:String(command.value),assetId:`user-${node.id}`}};if(command.type==="set-crop"&&node.kind==="image")return{...node,content:{...node.content,crop:String(command.value)}};return node;})});return versioned({...scene,pages,schemaVersion:undefined,revision:undefined,contentHash:undefined,upstreamHashes:undefined} as never,scene.revision+1,scene.upstreamHashes) as SceneGraph;
}
