import { randomUUID } from "node:crypto";
import { AssetPlanSchema, NarrativeOutlineSchema, PresentationBriefSchema, versioned, type AssetPlan, type DeckDesignPlan, type NarrativeOutline, type PageDesignIntent, type PresentationBrief, type QualityReport, type SceneGraph } from "@sparkdeck/presentation-model";
import { resolveDesignTokens, type DesignTokens } from "@sparkdeck/design-language";
import { composePage, type ResolvedCandidate } from "@sparkdeck/composition-engine";
import { applySceneCommand, compileSceneGraph } from "@sparkdeck/scene-graph";
import { buildVisualReviewBatch, evaluateScene } from "@sparkdeck/quality-engine";
import { exportSceneToPptx } from "@sparkdeck/pptx-export";
import type { Job } from "../../domain/jobs/job.js";
import type { GenerateImageUseCase } from "../use-cases/generate-image.use-case.js";
import { AppError } from "../../shared/errors/app-error.js";
import { DesignPlanner, NarrativePlanner, promptHash } from "./planning.service.js";

type Usage={id:string;provider:string;model:string;purpose:string;scopeId:string;requestHash:string;estimatedCostRmb:number;success:boolean;parentJob:string};
type RecordState={brief:PresentationBrief;outline?:NarrativeOutline;design?:{plan:DeckDesignPlan;intents:PageDesignIntent[]};tokens?:DesignTokens;candidates?:ResolvedCandidate[][];assetPlan?:AssetPlan;assets:Record<string,{url?:string;base64?:string;alt:string}>;scene?:SceneGraph;quality?:QualityReport;visualReview?:ReturnType<typeof buildVisualReviewBatch>;repairCount:number;history:SceneGraph[];future:SceneGraph[]};
export class PresentationPlatformService{
 private records=new Map<string,RecordState>();private jobs=new Map<string,Job>();private usage:Usage[]=[];private id=(prefix:string)=>`${prefix}_${randomUUID()}`;
 constructor(private narrative:NarrativePlanner,private designer:DesignPlanner,private image:GenerateImageUseCase|undefined){}
 create(input:Omit<PresentationBrief,"schemaVersion"|"revision"|"contentHash"|"upstreamHashes"|"id">){const id=this.id("pres"),brief=PresentationBriefSchema.parse(versioned({id,...input}));this.records.set(id,{brief,assets:{},repairCount:0,history:[],future:[]});return brief;}
 list(){return[...this.records.values()].map(r=>r.brief)}get(id:string){const value=this.records.get(id);if(!value)throw new AppError("PRESENTATION_NOT_FOUND","Presentation not found",404);return value}getJob(id:string){const job=this.jobs.get(id);if(!job)throw new AppError("JOB_NOT_FOUND","Job not found",404);return job}private newJob(scopeId:string,type:string):Job{const job={id:this.id("job"),scopeId,type,status:"queued" as const,progress:0,stage:"queued" as const,resultRef:null,error:null};this.jobs.set(job.id,job);return job}private update(job:Job,patch:Partial<Job>){Object.assign(job,patch);this.jobs.set(job.id,job)}private fail(job:Job,error:unknown){this.update(job,{status:"failed",progress:100,stage:"failed",error:{code:error instanceof AppError?error.code:"JOB_FAILED",message:error instanceof Error?error.message:"Job failed",incurredCost:false,freeRetryAllowed:true}})}
 startOutline(id:string){const state=this.get(id),job=this.newJob(id,"outline.generate");void(async()=>{try{this.update(job,{status:"running",stage:"planning",progress:20});const outline=await this.narrative.plan(state.brief);state.outline=outline;this.usage.push({id:this.id("usage"),provider:"dmx",model:"configured",purpose:"narrative",scopeId:id,requestHash:promptHash(state.brief),estimatedCostRmb:0,success:true,parentJob:job.id});this.update(job,{status:"succeeded",stage:"completed",progress:100,resultRef:outline.contentHash})}catch(e){this.fail(job,e)}})();return job}
 saveOutline(id:string,outline:unknown,expectedRevision:number){const state=this.get(id);if((state.outline?.revision??0)!==expectedRevision)throw new AppError("REVISION_CONFLICT","Outline revision conflict",409);state.outline=NarrativeOutlineSchema.parse(versioned({...NarrativeOutlineSchema.omit({schemaVersion:true,revision:true,contentHash:true,upstreamHashes:true}).parse(outline),briefId:id,confirmedAt:null},expectedRevision+1,{brief:state.brief.contentHash}));delete state.design;delete state.candidates;delete state.scene;return state.outline}
 confirmOutline(id:string,expectedRevision:number){const state=this.get(id);if(!state.outline)throw new AppError("OUTLINE_NOT_FOUND","Outline not found",404);if(state.outline.revision!==expectedRevision)throw new AppError("REVISION_CONFLICT","Outline revision conflict",409);state.outline={...state.outline,confirmedAt:new Date().toISOString(),revision:state.outline.revision+1};return state.outline}
 startDesign(id:string){const state=this.get(id),job=this.newJob(id,"design.generate");void(async()=>{try{if(!state.outline?.confirmedAt)throw new AppError("OUTLINE_NOT_CONFIRMED","Confirm outline first",409);this.update(job,{status:"running",stage:"planning",progress:20});state.design=await this.designer.plan(state.brief,state.outline);state.tokens=resolveDesignTokens(state.design.plan);this.usage.push({id:this.id("usage"),provider:"dmx",model:"configured",purpose:"design",scopeId:id,requestHash:promptHash(state.outline),estimatedCostRmb:0,success:true,parentJob:job.id});this.update(job,{status:"succeeded",stage:"completed",progress:100,resultRef:state.design.plan.contentHash})}catch(e){this.fail(job,e)}})();return job}
 compose(id:string,canvas={width:960,height:540}){const state=this.get(id),job=this.newJob(id,"composition.generate");try{if(!state.outline||!state.design||!state.tokens)throw new AppError("DESIGN_NOT_FOUND","Generate design first",409);this.update(job,{status:"running",stage:"generating_candidates",progress:20});state.candidates=state.outline.pages.map(page=>composePage(page,state.design!.intents.find(i=>i.pageId===page.id)!,canvas,state.tokens!));this.update(job,{stage:"scoring",progress:60});const placements=state.candidates.flatMap((set,index)=>{const selected=set.find(c=>c.selected)!;const page=state.outline!.pages[index]!,intent=state.design!.intents[index]!;const find=(n:ResolvedCandidate["resolved"],requestId:string):string|undefined=>n.sourceIds.includes(requestId)?n.id:n.children.map(c=>find(c,requestId)).find(Boolean);return intent.mediaRequests.map(request=>{const boundsRef=find(selected.resolved,request.id);if(!boundsRef)return null;const leaf=(function walk(n:ResolvedCandidate["resolved"]):ResolvedCandidate["resolved"]|undefined{return n.id===boundsRef?n:n.children.map(walk).find(Boolean)})(selected.resolved)!;return{id:`placement-${request.id}`,pageId:page.id,requestId:request.id,claimIds:request.claimIds,role:request.role,boundsRef,targetAspectRatio:leaf.bounds.width/leaf.bounds.height,fit:request.fit,focalPolicy:request.focalPolicy,...(request.textSafeArea?{textSafeArea:request.textSafeArea}:{})}}).filter((p):p is NonNullable<typeof p>=>Boolean(p))});state.assetPlan=AssetPlanSchema.parse(versioned({presentationId:id,placements,resolvedAssetIds:[]}));state.scene=compileSceneGraph({presentationId:id,outline:state.outline,intents:state.design.intents,candidateSets:state.candidates,tokens:state.tokens,canvas,assetPlan:state.assetPlan,assets:{}});this.update(job,{status:"succeeded",stage:"completed",progress:100,resultRef:state.scene.contentHash})}catch(e){this.fail(job,e)}return job}
 async resolveAssets(id:string){const state=this.get(id),job=this.newJob(id,"assets.resolve");try{if(!state.assetPlan||!state.scene||!state.design)throw new AppError("COMPOSITION_NOT_FOUND","Compose before assets",409);this.update(job,{status:"running",stage:"resolving_assets",progress:10});for(const [index,placement] of state.assetPlan.placements.entries()){const request=state.design.intents.flatMap(i=>i.mediaRequests).find(r=>r.id===placement.requestId)!;if(!this.image)continue;const result=await this.image.execute({prompt:[state.design.plan.illustrationDirection,request.description,`aspect ratio ${placement.targetAspectRatio.toFixed(3)}`,placement.textSafeArea?`text safe area ${placement.textSafeArea}`:""].filter(Boolean).join(". "),size:"1024x1024"}),assetId=this.id("asset");state.assets[assetId]={...(result.url?{url:result.url}:{}),...(result.base64?{base64:result.base64}:{}),alt:request.description};placement.assetId=assetId;state.assetPlan.resolvedAssetIds.push(assetId);this.usage.push({id:this.id("usage"),provider:"dmx",model:result.model,purpose:"image",scopeId:placement.id,requestHash:promptHash(request),estimatedCostRmb:result.estimatedCostRmb,success:true,parentJob:job.id});this.update(job,{progress:10+Math.round((index+1)/Math.max(1,state.assetPlan.placements.length)*80)})}state.scene=compileSceneGraph({presentationId:id,outline:state.outline!,intents:state.design.intents,candidateSets:state.candidates!,tokens:state.tokens!,canvas:state.scene.canvas,assetPlan:state.assetPlan,assets:Object.fromEntries(Object.entries(state.assets).map(([k,v])=>[k,{url:v.url,dataUri:v.base64?`data:image/png;base64,${v.base64}`:undefined,alt:v.alt}]))});this.update(job,{status:"succeeded",stage:"completed",progress:100,resultRef:state.scene.contentHash})}catch(e){this.fail(job,e)}return job}
 quality(id:string){const state=this.get(id),job=this.newJob(id,"quality.evaluate");try{if(!state.scene)throw new AppError("SCENE_NOT_FOUND","Scene not found",404);this.update(job,{status:"running",stage:"rule_quality",progress:50});state.quality=evaluateScene(state.scene);this.update(job,{stage:"visual_quality",progress:75});state.visualReview=buildVisualReviewBatch(state.scene,state.quality);this.update(job,{status:"succeeded",stage:"completed",progress:100,resultRef:state.quality.contentHash})}catch(e){this.fail(job,e)}return job}
 repair(id:string){const state=this.get(id),job=this.newJob(id,"quality.repair");try{if(!state.scene||!state.quality||!state.candidates||!state.outline||!state.design||!state.tokens)throw new AppError("QUALITY_NOT_FOUND","Run quality before repair",409);if(state.repairCount>=1)throw new AppError("REPAIR_LIMIT_REACHED","Automatic repair is limited to one pass",409);this.update(job,{status:"running",stage:"repairing",progress:30});const failed=new Set(state.quality.issues.filter(issue=>issue.severity==="error"&&issue.pageId).map(issue=>issue.pageId));state.candidates.forEach((set,index)=>{if(!failed.has(state.outline!.pages[index]?.id))return;const current=set.findIndex(candidate=>candidate.selected),next=set[(current+1)%set.length];if(next)set.forEach(candidate=>candidate.selected=candidate.id===next.id)});state.scene=compileSceneGraph({presentationId:id,outline:state.outline,intents:state.design.intents,candidateSets:state.candidates,tokens:state.tokens,canvas:state.scene.canvas,...(state.assetPlan?{assetPlan:state.assetPlan}:{}),assets:{}});state.repairCount++;state.quality={...evaluateScene(state.scene),repairCount:state.repairCount};this.update(job,{status:"succeeded",stage:"completed",progress:100,resultRef:state.quality.contentHash})}catch(e){this.fail(job,e)}return job}
 command(id:string,input:{type:"set-text"|"set-bounds"|"set-z"|"set-asset"|"set-crop";pageId:string;nodeId:string;value:unknown;expectedRevision:number}){const state=this.get(id);if(!state.scene)throw new AppError("SCENE_NOT_FOUND","Scene not found",404);state.history.push(state.scene);state.future=[];try{state.scene=applySceneCommand(state.scene,input)}catch{throw new AppError("REVISION_CONFLICT","Scene revision conflict",409)}delete state.quality;return state.scene}
 undo(id:string){const state=this.get(id),previous=state.history.pop();if(!previous||!state.scene)return state.scene;state.future.push(state.scene);state.scene=previous;return state.scene}redo(id:string){const state=this.get(id),next=state.future.pop();if(!next||!state.scene)return state.scene;state.history.push(state.scene);state.scene=next;return state.scene}
 selectCandidate(id:string,pageId:string,candidateId:string,expectedRevision:number){const state=this.get(id);if(!state.scene||state.scene.revision!==expectedRevision)throw new AppError("REVISION_CONFLICT","Scene revision conflict",409);const index=state.outline?.pages.findIndex(p=>p.id===pageId)??-1,set=state.candidates?.[index],chosen=set?.find(c=>c.id===candidateId);if(!chosen)throw new AppError("CANDIDATE_NOT_FOUND","Candidate not found",404);set!.forEach(c=>c.selected=c.id===candidateId);state.scene=compileSceneGraph({presentationId:id,outline:state.outline!,intents:state.design!.intents,candidateSets:state.candidates!,tokens:state.tokens!,canvas:state.scene.canvas,assetPlan:state.assetPlan,assets:{}});return state.scene}
 async export(id:string){const state=this.get(id);if(!state.scene)throw new AppError("SCENE_NOT_FOUND","Scene not found",404);if(!state.quality?.passed)throw new AppError("QUALITY_GATE_FAILED","Quality gate has not passed",409);return exportSceneToPptx(state.scene)}usageLedger(id:string){const jobIds=new Set([...this.jobs.values()].filter(job=>job.scopeId===id).map(job=>job.id));return this.usage.filter(item=>jobIds.has(item.parentJob))}
}
